#!/system/bin/sh
export LD_PRELOAD=libcpc_extension_jni.xiaomi.so
export CLASSPATH=/data/local/tmp/CpcSocketTest.jar:/system/framework/cpc-extension.jar:/system/framework/android.test.runner.jar
exec app_process /system/bin android.net.CpcSocketTest "$@"
