#!/system/bin/sh
export LD_PRELOAD=libcpc_extension_jni.xiaomi.so
export CLASSPATH=/data/local/tmp/CpcPropertiesTest.jar:/system/framework/cpc-extension.jar
exec app_process /system/bin android.os.CpcPropertiesTest "$@"
